package br.com.sugestaopedidos.backend.client;

import br.com.sugestaopedidos.backend.client.schema.Message;
import br.com.sugestaopedidos.backend.client.schema.Role;

public class Scripts {

    private static final String CONTENT_RETURN_FORMAT =
            "Forneça a resposta no formato JSON, sem caracteres especiais, seguindo esta estrutura: " +
                    "{ \"title\": \"Nome do prato\", \"message\": \"Motivo da escolha.\" }";
    private static final String CONTENT_ERROR_RESTAURANT = "Se o usuário demonstrar preferência por um restaurante específico e não quiser considerar outras opções, me avise com a seguinte mensagem: { \"title\": \"USER COM PREFERÊNCIA\", \"message\": \"O usuário já tem um restaurante em mente e não deseja escolher outro.\"}.  Se o cliente perguntar algo não relacionado a restaurantes, informe que este bot é especializado apenas em recomendações de restaurantes, me avise com a seguinte mensagem: { \"title\": \"NÃO RELACIONADO\", \"message\": \"[sua mensagem de erro]\"}.";
    private static final String CONTENT_ERROR_MENU_ITEM = "Se o usuário demonstrar preferência por um restaurante específico e não quiser considerar outras opções, me avise com a seguinte mensagem: {\\\"titulo\\\": \\\"USER COM PREFERÊNCIA\\\", \\\"mensagem\\\": \\\"O usuário já tem um restaurante em mente e não deseja escolher outro.\\\"}";
    private static final String CONTENT_SCRIPT_RESTAURANT = "Você é um Sistema de Sugestão para Restaurantes utilizando Inteligência Artificial. Sua função é ajudar o cliente a escolher um restaurante. Se o cliente mencionar um restaurante que não está na lista, sugira uma opção semelhante.";
    private static final String REFUSAL_SCRIPT_RESTAURANT = "Desculpe, só posso ajudar com sugestões de restaurantes.";
    private static final String CONTENT_SCRIPT_MENU_ITEM = "Você é um Sistema de Sugestão para Restaurantes utilizando Inteligência Artificial. Sua função é ajudar o cliente a escolher um prato. Se o cliente mencionar um prato que não está no cardápio, sugira uma opção semelhante. Se o cliente perguntar algo não relacionado a restaurantes, responda educadamente que este bot é especializado apenas em recomendações de pratos.";
    private static final String REFUSAL_SCRIPT_MENU_ITEM = "Desculpe, só posso ajudar com sugestões de pratos do restaurante.";
    public static final Message RETURN_FORMAT = new Message(Role.system, CONTENT_RETURN_FORMAT);
    public static final Message ERROR_RESTAURANT = new Message(Role.system, CONTENT_ERROR_RESTAURANT);
    public static final Message ERROR_MENU_ITEM = new Message(Role.system, CONTENT_SCRIPT_RESTAURANT);
    public static final Message SCRIPT_RESTAURANT = new Message(Role.system, CONTENT_SCRIPT_RESTAURANT);
    public static final Message SCRIPT_MENU_ITEM = new Message(Role.system, CONTENT_SCRIPT_MENU_ITEM);

    public static final Message TEST_RESTAURANT =
            new Message(Role.system,
                    "segue a lista de restaurantes:Casa do Marisco Tipo de comida: Especializado em frutos do mar frescos, como amêijoas, lagostas, camarões e peixes grelhados. Ambiente: À beira-mar, com decoração rústica e vista para o oceano. Ideal para jantares românticos ou reuniões familiares. Tasca do Zé Tipo de comida: Comida tradicional portuguesa, como bacalhau à brás, feijoada e cozido à portuguesa. Ambiente: Descontraído e acolhedor, com mesas de madeira e paredes decoradas com azulejos típicos. Perfeito para quem quer uma experiência autêntica. Sushi Ya Tipo de comida: Sushi, sashimi e pratos japoneses contemporâneos, com opções vegetarianas e veganas. Ambiente: Moderno e minimalista, com iluminação suave e música ambiente. Ideal para refeições rápidas ou encontros informais. La Trattoria Tipo de comida: Massas frescas, pizzas artesanais e pratos clássicos da culinária italiana. Ambiente: Aconchegante e familiar, com decoração rústica e um forno a lenha visível na área de preparação. Churrasqueira do Bairro Tipo de comida: Carnes grelhadas no carvão, como frango assado, costeletas de porco e espetadas mistas. Ambiente: Informal e barulhento, com mesas compartilhadas e um aroma irresistível de churrasco no ar. Veggie Garden Tipo de comida: Comida vegetariana e vegana, com pratos criativos como hambúrgueres de legumes, bowls coloridos e sobremesas sem lactose. Ambiente: Descontraído e ecológico, com decoração natural e um pequeno jardim interno. O Forno da Avó Tipo de comida: Pratos caseiros e sobremesas tradicionais, como arroz doce, leite-creme e bolos regionais. Ambiente: Aconchegante e nostálgico, com móveis antigos e um cheiro de doce que lembra a casa da avó. Bistro Parisiense Tipo de comida: Culinária francesa, como foie gras, escargots, boeuf bourguignon e crème brûlée. Ambiente: Elegante e sofisticado, com toalhas de mesa brancas e iluminação suave. Ideal para ocasiões especiais. Cantinho da Índia Tipo de comida: Pratos indianos picantes e aromáticos, como curry, tandoori e naan. Ambiente: Colorido e vibrante, com música tradicional indiana e decoração exótica. Burger Mania Tipo de comida: Hamburgueres gourmet, com opções de carne, frango, peixe e veganos, acompanhados de batatas fritas artesanais. Ambiente: Moderno e descontraído, com paredes grafitadas e música pop animada. Perfeito para jovens e famílias.");
    public static final Message TEST_MENU_ITEM =
            new Message(Role.system,
                    "segue a lista dos pratos:Arroz de Marisco => Um clássico português, feito com arroz, camarões, amêijoas, mexilhões e lagostim, temperado com um caldo de peixe rico e aromático. Cataplana de Marisco=>Um prato tradicional algarvio, preparado em uma panela de cobre, com uma mistura de mariscos, peixe, linguiça, tomate, pimentão e ervas. Lagosta Grelhada com Manteiga de Alho=>Lagosta fresca grelhada, servida com uma manteiga derretida aromatizada com alho e ervas, acompanhada de legumes grelhados. Amêijoas à Bulhão Pato=>Amêijoas frescas cozidas em azeite, alho, coentros e vinho branco, servidas com pão para aproveitar o molho. Polvo à Lagareiro=>Polvo cozido e depois assado no forno com azeite, batatas cozidas e alhos, resultando em um prato simples mas saboroso.Sopa de Peixe=>Uma sopa rica e reconfortante, feita com vários tipos de peixe, mariscos, tomate, batata e especiarias, servida com croutons.Bacalhau Assado com Natas=>Bacalhau desfiado, misturado com natas, cebola e batata, gratinado no forno até ficar dourado.=>Espetada de Camarão e Lula=>Camarões e lulas grelhados em espetos, marinados em azeite, limão, alho e pimentão, servidos com arroz de ervas.=>Filete de Dourada Grelhada=>Filetes de dourada grelhados na perfeição, servidos com um molho de limão e endro, acompanhados de legumes salteados.=>Mousse de Marisco=>Uma entrada leve e cremosa, feita com mariscos triturados, creme de leite e especiarias, servida com torradas ou biscoitos salgados.");

}
